Fix pipeline build failing due to test not recognizing 'dispatch' as a function. Actual error message: 'TypeError: dispatch is not a function.' Strange and awkward. Fixed. We move.